matrix:
  include:
    - language: go # Build and Test
      go:
        - 1.13.x
      sudo: true
      # Derived from https://github.com/lib/pq/blob/master/.travis.yml
      env:
        - GO111MODULE=on
        - FBM_DB_CONN=postgres://fbm:secret@127.0.0.1/fbm
        - PGVERSION=12
      script:
        - ./travis/before_install.bash
        - ./travis/before_script.bash
        - ./travis/script.bash
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - language: minimal  # Build on master
      env:
        - REGISTRY=docker.pkg.github.com/bitmark-inc/spring-app-api
      services:
        - docker
      if: branch = master AND fork = false
      before_script:
        - export VERSION="commit-$(git rev-parse --short ${TRAVIS_COMMIT})"
        - echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u "$DOCKER_USERNAME" --password-stdin  # Login to GitHub Registry using Travis environment variables
      script:
        - docker build --build-arg dist=$VERSION -t $REGISTRY/api:$VERSION . || { echo 'build failed' ; exit 1; }
        - docker build --build-arg dist=$VERSION -t $REGISTRY/background:$VERSION -f Dockerfile-Jobs . || { echo 'build failed' ; exit 1; }
      after_success:
        - docker push $REGISTRY/api:$VERSION
        - docker push $REGISTRY/background:$VERSION
    - language: minimal  # Build on tag
      env:
        - REGISTRY=docker.pkg.github.com/bitmark-inc/spring-app-api
      services:
        - docker
      if: tag IS present
      before_script:
        - echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u "$DOCKER_USERNAME" --password-stdin  # Login to GitHub Registry using Travis environment variables
        - export API_DOCKER_IMG=$REGISTRY/api:$TRAVIS_TAG
        - export BACKGROUND_DOCKER_IMG=$REGISTRY/background:$TRAVIS_TAG
        - export RELEASE_BODY=`cat ./travis/release_template.md | sed -e 's@SPRING_VERSION@'"$TRAVIS_TAG"'@g;s@API_DOCKER_IMG@'"$API_DOCKER_IMG"'@g;s@BACKGROUND_DOCKER_IMG@'"$BACKGROUND_DOCKER_IMG"'@g'`
      script:
        - docker build --build-arg dist=$TRAVIS_TAG -t $API_DOCKER_IMG . || { echo 'build failed' ; exit 1; }
        - docker build --build-arg dist=$TRAVIS_TAG -t $BACKGROUND_DOCKER_IMG -f Dockerfile-Jobs . || { echo 'build failed' ; exit 1; }
      after_success:
        - docker push $API_DOCKER_IMG
        - docker push $BACKGROUND_DOCKER_IMG
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        overwrite: true
        skip_cleanup: true
        target_commitish: $TRAVIS_COMMIT
        tag_name: $TRAVIS_TAG
        draft: false
        prerelease: true
        on:
          tags: true