matrix:
  include:
    - language: go # Build and Test
      go:
        - 1.13.x
      sudo: true
      # Derived from https://github.com/lib/pq/blob/master/.travis.yml
      env:
        - GO111MODULE=on
        - FBM_DB_CONN=postgres://fbm:secret@127.0.0.1/fbm
        - PGVERSION=12
      script:
        - ./travis/before_install.bash
        - ./travis/before_script.bash
        - ./travis/script.bash
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - language: minimal  # Build on master
      env:
        - REGISTRY=docker.pkg.github.com/bitmark-inc/spring-app-api
      services:
        - docker
      if: branch = master AND fork = false
      before_script:
        - export VERSION="release-$(git rev-parse --short ${TRAVIS_COMMIT})"
        - echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u "$DOCKER_USERNAME" --password-stdin  # Login to GitHub Registry using Travis environment variables
      script:
        - docker build --build-arg dist=$VERSION -t $REGISTRY/api:git-$VERSION . || { echo 'build failed' ; exit 1; }
        - docker build --build-arg dist=$VERSION -t $REGISTRY/background:git-$VERSION -f Dockerfile-Jobs . || { echo 'build failed' ; exit 1; }
      after_success:
        - docker push $REGISTRY/api:git-$VERSION
        - docker push $REGISTRY/background:git-$VERSION
    - language: minimal  # Build on tag
      env:
        global:
          - REGISTRY=docker.pkg.github.com/bitmark-inc/spring-app-api
      services:
        - docker
      if: tag IS present
      before_script:
        - echo "$GITHUB_TOKEN" | docker login docker.pkg.github.com -u "$DOCKER_USERNAME" --password-stdin  # Login to GitHub Registry using Travis environment variables
      script:
        - docker build --build-arg dist=$TRAVIS_TAG -t $REGISTRY/api:$TRAVIS_TAG . || { echo 'build failed' ; exit 1; }
        - docker build --build-arg dist=$TRAVIS_TAG -t $REGISTRY/background:$TRAVIS_TAG -f Dockerfile-Jobs . || { echo 'build failed' ; exit 1; }
      after_success:
        - docker push $REGISTRY/api:git-$TRAVIS_TAG
        - docker push $REGISTRY/background:git-$TRAVIS_TAG