FROM golang:1.13-alpine as build

WORKDIR $GOPATH/github.com/bitmark-inc/spring-app-api

ADD go.mod .
ADD go.sum .

RUN go mod download

ADD . .

WORKDIR $GOPATH/github.com/bitmark-inc/spring-app-api/background
RUN go install github.com/bitmark-inc/spring-app-api/background

# ---

FROM alpine:3.10
ARG dist=0.0
COPY --from=build /go/bin/background /

ENV FBM_LOG_LEVEL=INFO
ENV FBM_SERVER_VERSION=$dist

CMD ["/background"]
